################################################################################
#
# PetNameProvider is a Faker provider of 255 the most popular pet names
#
# Copyright 2026 John Rofrano. All Rights Reserved.
#
################################################################################
# cspell: disable

"""
Faker Provider for Pet Names

  Usage:
    fake = Faker()
    fake.seed_instance(42)
    fake.add_provider(PetNameProvider)
    print(fake.pet_name())

"""

from faker import Faker
from faker.providers import BaseProvider


class PetNameProvider(BaseProvider):
    """Pet Name Provider for Faker"""

    pet_names = [
        "Abigail",
        "Ace",
        "Adam",
        "Addie",
        "Admiral",
        "Aggie",
        "Aires",
        "Aj",
        "Ajax",
        "Aldo",
        "Alex",
        "Alexus",
        "Alf",
        "Alfie",
        "Allie",
        "Ally",
        "Amber",
        "Amie",
        "Amigo",
        "Amos",
        "Amy",
        "Andy",
        "Angel",
        "Angus",
        "Annie",
        "Apollo",
        "April",
        "Archie",
        "Argus",
        "Aries",
        "Armanti",
        "Arnie",
        "Arrow",
        "Ashes",
        "Ashley",
        "Astro",
        "Athena",
        "Atlas",
        "Audi",
        "Augie",
        "Aussie",
        "Austin",
        "Autumn",
        "Axel",
        "Axle",
        "Babbles",
        "Babe",
        "Baby",
        "Baby-doll",
        "Babykins",
        "Bacchus",
        "Bailey",
        "Bam-bam",
        "Bambi",
        "Bandit",
        "Banjo",
        "Barbie",
        "Barclay",
        "Barker",
        "Barkley",
        "Barley",
        "Barnaby",
        "Barney",
        "Baron",
        "Bart",
        "Basil",
        "Baxter",
        "Bb",
        "Beamer",
        "Beanie",
        "Beans",
        "Bear",
        "Beau",
        "Beauty",
        "Beaux",
        "Bebe",
        "Beetle",
        "Bella",
        "Belle",
        "Ben",
        "Benji",
        "Benny",
        "Benson",
        "Bentley",
        "Bernie",
        "Bessie",
        "Biablo",
        "Bibbles",
        "Big Boy",
        "Big Foot",
        "Biggie",
        "Billie",
        "Billy",
        "Bingo",
        "Binky",
        "Birdie",
        "Birdy",
        "Biscuit",
        "Bishop",
        "Gus",
        "Guy",
        "Gypsy",
        "Hailey",
        "Haley",
        "Hallie",
        "Hamlet",
        "Hammer",
        "Hank",
        "Hanna",
        "Hannah",
        "Hans",
        "Happy",
        "Hardy",
        "Harley",
        "Harpo",
        "Harrison",
        "Harry",
        "Harvey",
        "Heather",
        "Heidi",
        "Henry",
        "Hercules",
        "Hershey",
        "Higgins",
        "Hobbes",
        "Holly",
        "Homer",
        "Honey",
        "Honey-Bear",
        "Hooch",
        "Hoover",
        "Hope",
        "Houdini",
        "Howie",
        "Hudson",
        "Huey",
        "Hugh",
        "Hugo",
        "Humphrey",
        "Hunter",
        "India",
        "Indy",
        "Iris",
        "Isabella",
        "Isabelle",
        "Itsy",
        "Itsy-bitsy",
        "Ivory",
        "Ivy",
        "Izzy",
        "Jack",
        "Jackie",
        "Jackpot",
        "Jackson",
        "Jade",
        "Jagger",
        "Jags",
        "Jaguar",
        "Jake",
        "Jamie",
        "Jasmine",
        "Jasper",
        "Jaxson",
        "Jazmie",
        "Jazz",
        "Jelly",
        "Jelly-bean",
        "Jenna",
        "Jenny",
        "Jerry",
        "Jersey",
        "Jess",
        "Jesse",
        "Jesse James",
        "Jessie",
        "Jester",
        "Jet",
        "Jethro",
        "Jett",
        "Jetta",
        "Jewel",
        "Jewels",
        "Jimmy",
        "Jingles",
        "JJ",
        "Joe",
        "Joey",
        "Johnny",
        "Jojo",
        "Joker",
        "Jolie",
        "Jolly",
        "Jordan",
        "Josie",
        "Joy",
        "JR",
        "Judy",
        "Julius",
        "June",
        "Misty",
        "Mitch",
        "Mittens",
        "Mitzi",
        "Mitzy",
        "Mo",
        "Mocha",
        "Mollie",
        "Molly",
        "Mona",
        "Muffy",
        "Nakita",
        "Nala",
        "Nana",
        "Natasha",
        "Nellie",
        "Nemo",
        "Nena",
        "Peanut",
        "Peanuts",
        "Pearl",
        "Pebbles",
        "Penny",
        "Phoebe",
        "Phoenix",
        "Sara",
        "Sarah",
        "Sasha",
        "Sassie",
        "Sassy",
        "Savannah",
        "Scarlett",
        "Shasta",
        "Sheba",
        "Sheena",
        "Shelby",
        "Shelly",
        "Sienna",
        "Sierra",
        "Silky",
        "Silver",
        "Simone",
        "Sissy",
        "Skeeter",
        "Sky",
        "Skye",
        "Skyler",
        "Waldo",
        "Wallace",
        "Wally",
        "Walter",
        "Wayne",
        "Weaver",
        "Webster",
        "Wesley",
        "Westie",
    ]

    def pet_name(self):
        """Generates a random pet name

        Returns:
            str: The name of a pet
        """
        return self.random_element(self.pet_names)


class PetNameFaker(Faker):
    """Custom Faker that includes the pet names provider"""

    def __init__(self) -> None:
        super().__init__()
        self.add_provider(PetNameProvider)

    def name(self):
        """Generates a random pet name"""
        return self.pet_name()
